# Generated by Django 4.2.11 on 2026-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите содержимое статьи', verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение для статьи', null=True, upload_to='blog/', verbose_name='Превью (изображение)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания статьи', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, help_text='Отметьте, если статья опубликована', verbose_name='Признак публикации')),
                ('views_count', models.IntegerField(default=0, help_text='Количество просмотров статьи', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блоговая запись',
                'verbose_name_plural': 'Блоговые записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
